openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: API for managing tasks with features like creation, listing, searching, updating, and notifications.
servers:
  - url: http://127.0.0.1:8000/api
paths:
  /tasks:
    get:
      summary: List all tasks
      parameters:
        - in: query
          name: status
          schema:
            type: integer
          description: Filter by task status (1=Pending, 2=In Progress, 3=Completed, 4=Overdue)
        - in: query
          name: start_date
          schema:
            type: string
            format: date (Y-m-d)
          description: Filter from due date
        - in: query
          name: end_date
          schema:
            type: string
            format: date (Y-m-d)
          description: Filter to due date
        - in: query
          name: sort_by
          schema:
            type: string
            enum: [created_at, due_date, priority]
          description: Field to sort by
        - in: query
          name: sort_direction
          schema:
            type: string
            enum: [asc, desc]
          description: Sort direction
          - in: query
          name: text_search
          schema:
            type: string
          description: filter the tasks according to the text search
      responses:
        '200':
          description: List of tasks
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - due_date
              properties:
                title:
                  type: string
                description:
                  type: string
                due_date:
                  type: string
                  format: date-time
                priority:
                  type: integer
                  description: 1=Low, 2=Medium, 3=High
      responses:
        '201':
          description: Task created
        '429':
          description: Too many requests (Rate Limited)
  /tasks/{id}/status:
    patch:
      summary: Update task status
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: integer
                  description: 1=Pending, 2=In Progress, 3=Completed, 4=Overdue
      responses:
        '200':
          description: Task status updated
  /tasks/{id}:
    delete:
      summary: Soft delete a task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task soft deleted
  /notifications/check-upcoming-tasks:
    get:
      summary: Trigger command to check for upcoming tasks (within 24 hours)
      description: Custom artisan command scheduled hourly to queue email notifications for tasks due in 24 hours.
      responses:
        '200':
          description: Command executed and matching tasks queued for notification
